#!/bin/bash
# shellcheck disable=SC2016,SC2046,SC2066,SC2068,SC2086,SC2162,SC2317

clear

##
## set the available cpu thread and core count for parallel processing (speeds up the build process)
##

if [ -f '/proc/cpuinfo' ]; then
    cpu_threads="$(grep -c ^processor '/proc/cpuinfo')"
else
    cpu_threads="$(nproc --all)"
fi
cpu_cores="$(grep ^cpu\\scores '/proc/cpuinfo' | uniq | awk '{print $4}')"

build_mod(){
    # Copy over the modules, unmount the img now that we're done with it: 
    tar -cJvf "$PWD/modules.xz" "$PWD/modules"
}

cd  "linux-msft-wsl"
make KCONFIG_CONFIG=../config-wsl INSTALL_MOD_PATH="$PWD/modules" modules_install  -j "$cpu_cores"
build_mod
